version: "3.8"
services:
  backend:
    build: .
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - logs:/app/logs
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgweb:
    image: sosedoff/pgweb:0.13.1
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_db_data:/data
      
  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 5555:5555
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PORT: 5555
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
    depends_on:
      - redis

volumes:
  postgres_data:
  logs:
  redis_db_data:
    external: false